version: '3.8'
services:
  bot:
    build: .
    container_name: mystic_trader_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - TZ=UTC
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    # Add any environment variables your bot needs